export const abbrs = {
  EST: 'Eastern Standard Time',
  EDT: 'Eastern Daylight Time',
  CST: 'Central Standard Time',
  CDT: 'Central Daylight Time',
  MST: 'Mountain Standard Time',
  MDT: 'Mountain Daylight Time',
  PST: 'Pacific Standard Time',
  PDT: 'Pacific Daylight Time',
  GMT: 'Greenwich Mean Time',
  EAT: 'East Africa Time',
  CET: 'Central European Time',
  WAT: 'West Africa Time',
  CAT: 'Central Africa Time',
  EET: 'Eastern European Time',
  CEST: 'Central European Summer Time',
  SAST: 'South African Standard Time',
  HDT: 'Hawaii-Aleutian Daylight Time',
  AKDT: 'Alaska Daylight Time',
  AST: 'Atlantic Standard Time',
  ADT: 'Atlantic Daylight Time',
  NDT: 'Newfoundland Daylight Time',
  NZST: 'New Zealand Standard Time',
  EEST: 'Eastern European Summer Time',
  IST: 'India Standard Time',
  HKT: 'Hong Kong Time',
  WIB: 'Western Indonesian Time',
  WIT: 'Eastern Indonesian Time',
  IDT: 'Israel Daylight Time',
  PKT: 'Pakistan Standard Time',
  WITA: 'Central Indonesian Time',
  KST: 'Korea Standard Time',
  JST: 'Japan Standard Time',
  WEST: 'Western European Summer Time',
  AEST: 'Australian Eastern Standard Time',
  ACST: 'Australian Central Standard Time',
  AWST: 'Australian Western Standard Time',
  UTC: 'Coordinated Universal Time',
  BST: 'British Summer Time',
  MSK: 'Moscow Standard Time',
  HST: 'Hawaii–Aleutian Standard Time',
  MEST: 'Middle European Summer Time',
  ChST: 'Chamorro Standard Time',
  SST: 'Samoa Standard Time',
};
